[package]
name = "sensor-api"
version = "0.1.0"
authors = ["scullionw <scuw1801@usherbrooke.ca>"]
edition = "2018"

[dependencies]
rocket = "0.4.0-rc.1"
rocket_contrib = "0.4.0-rc.1"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"