[development]
address = "localhost"
port = 8000
log = "normal"
secret_key = 'UbRZS0Zhkt6BQkDydi6zxBTvF7GpC7xUElkLh+GG1qc='

[production]
address = "0.0.0.0" # Any interface
port = 8000
log = "normal"
secret_key = 'UbRZS0Zhkt6BQkDydi6zxBTvF7GpC7xUElkLh+GG1qc=' # Generate with openssl rand -base64 32